### PR TITLE
imp: make script faster and with less dependencies

### PR DESCRIPTION
**Pull request by flexagoon**

### CODE REVIEW

**Comment by coffebar** [comment]
Hi thanks for the contribution. I have tested this version and found that it does not work in Chrome. 
It works for example in VSCode, but Chrome is a most common app. Have you checked this case? 
Master branch _Hukuta/layout_corrector_ is working for me in Chrome.

**Comment by flexagoon** [comment]
I tested it in QuteBrowser, which is Chromium-based. Let me install chromium quickly, I'll tell you when I finish

**Comment by flexagoon** [comment]
Yes, it does indeed work in Chrome on my system.

It's werid that it doesn't for you, because my commit doesnt add or remove any feaures, it just replaces three different programs that do one thing with one program that does the same thing

**Comment by coffebar** [comment]
When I wrote the very first version, I also wanted to use  xdotool, but i found that xvkbd is working as expected on more programs in my system. So I had to move to xvkbd.

**Pull request closed without merging**
